root = "."
tmp_dir = "tmp"

[build]
args_bin = ["--port", "8080"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/app"
delay = 1000
exclude_dir = ["node_modules", "tmp", "internal/server/public/js"]
exclude_file = ["internal/server/public/style.min.css"]
exclude_regex = ["_test.go$", "_templ.go$", "\\.min\\.js$", "\\.min\\.css$"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = [
    "go",
    "templ",
    "html",
    "css",
    "js",
    "tsx",
    "ts",
    "yaml",
    "yml",
    "txt",
]
include_file = []
kill_delay = "1s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = ["pnpm run styles", "templ generate", "pnpm run islands"]
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 4321

[screen]
clear_on_rebuild = false
keep_scroll = true
