package ai

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// for files generated by ai
var tempDir string

func init() {
	var err error
	tempDir, err = os.MkdirTemp("", "gameslabor")
	if err != nil {
		panic(err)
	}
}

func Handler(w http.ResponseWriter, r *http.Request) {
	filename := filepath.Join(tempDir, strings.TrimPrefix(r.URL.Path, "/ai/"))
	http.ServeFile(w, r, filename)
}

func Cleanup() {
	_ = os.RemoveAll(tempDir)
}

func saveMp3(audio []byte) (string, error) {
	filename := filepath.Join(tempDir, uuid.New().String()+".mp3")
	return filename, os.WriteFile(filename, audio, 0644)
}
